[username]
show_always = true
format = "[✩‧₊ hakasax ₊‧✩](bold #ff0084) "
[character]
format = "[$symbol](bold #8908f9) "
success_symbol = "➜ "
[git_branch]
disabled = true
[directory]
style = "bold #5a70ff"
format = "$path "